### PR TITLE
Add 2 more companies

### PR DESCRIPTION
**Pull request by samuelsteiner**

### CODE REVIEW

**Comment by staltz** [comment]
Hi @samuelsteiner , it's great when a company is giving back tools to the community. For inclusion in this list we also require that the company makes a public statement about supporting 3rd party open source, not just (first-party) open source projects where the copyright holder is Airbnb.

**Comment by samuelsteiner** [comment]
@staltz Actually, AirBnB just got in there because I have forked from this repo. Have removed it now. We're actively supporting 3rd party open source (e.g. cancancan).

**Comment by coorasse** [comment]
@staltz any update regarding this PR? Shall we do something else?

**Comment by staltz** [comment]
Hi! I found the section "Social Responsibility" [here](https://www.renuo.ch/en/story) and will merge on the basis of donating to Wikimedia which builds the software MediaWiki.

**Pull request merged**
