### PR TITLE
Add Microsoft

### PR DESCRIPTION
**Pull request by Brocco**
Microsoft's open source info can be found here: https://opensource.microsoft.com/

### CODE REVIEW

**Comment by staltz** [comment]
Hi @Brocco. Does Microsoft support 3rd party open source projects? (Read more in the criteria placed in the readme.md)

**Comment by furkanmustafa** [comment]
Unfortunately, yes, microsoft is supporting many open source projects, just for vanity. An unfortunate example; http://www.apache.org/foundation/thanks.html and I believe there are way more unfortunate examples.

**Comment by molant** [comment]
@furkanmustafa why unfortunately?

Microsoft is also a platinum [member of the Linux foundation](https://www.linuxfoundation.org/members/corporate), with contributors to the kernel and node among others, and [one of the top open source companies in GitHub](https://www.theverge.com/2016/9/15/12926288/microsoft-really-does-love-linux).

What is missing in this PR to get it merged?

**Comment by staltz** [comment]
We were just missing the links you just posted. :)

**Pull request merged**
