### PR TITLE
Add SurviveJS Oy

### PR DESCRIPTION
**Pull request by bebraw**
Open source content + development time (single developer) + sponsorship (30% of webpack book to Tobias).

### CODE REVIEW

**Comment by staltz** [comment]
Hi @bebraw. We just clarified the criteria for each entry at the top of the README.md, it would be necessary to link to some page demonstrating the support to open source projects.

**Comment by bebraw** [comment]
How to prove that a part of royalty goes to a third party (in this case webpack) as there's no publicly available information on that?

**Comment by bebraw** [comment]
Can you give instructions on how to provide that `missing something`?

**Comment by staltz** [comment]
Hi @bebraw, as said above:

> it would be necessary to link to some page demonstrating the support to open source projects.

You can look at links to other companies to see examples of what that means.

**Pull request closed without merging**
