### PR TITLE
Add Metosin and Reaktor

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by staltz** [comment]
Hi @phadej, notice we're looking for third-party open source support, so projects licensed under the company are not third-party. If I understood correctly, Reaktor does that with Bluebird, but libraries from Metosin are licensed under Metosin Oy.

**Comment by phadej** [comment]
I removed metosin :(

**Comment by staltz** [comment]
@kof @mxstbr I need your opinion on how we can include companies that make many modules as open source, such as Metosin, without including any company that open sources a single 100-line gist.

One idea I have is to make a separate list. This list can stay for supporters of third-party projects, and then another list can be of companies that dedicate a good portion of their time producing open source, although finding the exact criteria for that will also prove complicated.

For now, I'm merging this one.

**Comment by kof** [comment]
I think our metrics should  be not whether a company open sourced something or not, but rather if they are investing reasonable time or money on a constant basis and able to proof that.

**Comment by Deraen** [comment]
Metosin employees also contribute to third party projects (during work). We just don't have current any "Supported by" notices or list of projects we have contributed to.

For example, I am one of maintainers of https://github.com/reagent-project/reagent/commits/master and https://github.com/cljsjs/packages. I have also done some work on ClojureScript compiler. These are just some of projects I have contributed to, but these three are those that I most often contribute to during working hours.

I guess the best way to prove this would be to extend our website to describe our contributions, with links to the projects?

**Comment by kof** [comment]
@Deraen was you able to work on it mostly during the work or in spare time? @staltz I think we need a standard way for companies to express their contributions.

**Comment by Deraen** [comment]
Most work I have done on Reagent and ClojureScript compiler is during work. Cljsjs is harder to categorize,  but some of that is during work. To give some estimate of amount of the work, 8% of my logged hours this year are logged to "opensource project". And this doesn't include the cases where I have contributed to a OS project as part of a customer project, though I guess those don't count as sponsoring anyway.

**Comment by staltz** [comment]
@Deraen That's good to know, and yes, the simplest and clearest way forward would be to put on the website as you said:

> I guess the best way to prove this would be to extend our website to describe our contributions, with links to the projects?

Would work well even as a one sentence here: http://www.metosin.fi/metosin/

It may feel like a mere modification of site just to pass the criteria for this list, but on a wider perspective, we are making third-party open source contributions more visible, instead of being shy about it, and hopefully this will change the industry.

- - -

@kof 
> I think we need a standard way for companies to express their contributions.

How about these website statements? I don't think we can get auditable / verifiable proof, we need to rely on companies being honest (for their own good, in the long term).

**Comment by kof** [comment]
> How about these website statements? I don't think we can get auditable / verifiable proof, we need to rely on companies being honest (for their own good, in the long term).

Yes we def. have to rely on their honesty, but we need to get as precise statements as possible. So that there is no way they don't do it, because long term people will notice that and let us know. It is a crowd based verification we can establish.

Thats why I created #30 in order to find some format for them which defines what has to be in their statement. If it should be a website or a .txt file etc.

**Pull request merged**
