### PR TITLE
Add cwd.at GmbH

### PR DESCRIPTION
**Pull request by theofidry**
[cwd.at GmbH](https://cwd.at/) is an Austrian company which lets its employees work on various Open Source projects such as [Symfony](https://github.com/symfony/symfony), [PhpScoper](https://github.com/humbug/php-scoper), [Puli](http://docs.puli.io/en/latest/) and [Alice](https://github.com/nelmio/alice).

### CODE REVIEW

**Comment by staltz** [comment]
Thanks. I'll wait until someone who knows german can review it. :)

**Comment by theofidry** [comment]
Google translator should be enough for this one though :P

**Comment by Simperfit** [comment]
@staltz We can merge this one, I know german and the people in the company ;)

**Review by Simperfit — APPROVED** [review]

**Comment by staltz** [comment]
Hi. I used a simple translator and wasn't able to find proof of open source support according to the criteria we have for the list: 

> Each entry is a COMPANY which systematically SUPPORTS some THIRD-PARTY OPEN SOURCE PROJECTS.

> Each entry should list the: (1) COMPANY name, (2) link(s) to blog post or page proving the support.

> SUPPORT (verb): to donate money to maintainers of an OPEN SOURCE PROJECT, or to allocate time for employees to contribute to OPEN SOURCE PROJECTS.

**Comment by theofidry** [comment]
@staltz there's no statement on the website, however [my github projects](https://github.com/theofidry), [webmozart's one](https://github.com/webmozart) as well as the [company open sourced projects](https://github.com/cwd) can attest of its support (although this year we had to slow down a bit on that side last year).

I'll ask for a statement to be made on the website still.

**Comment by theofidry** [comment]
Update: statement added to the website :)

**Pull request merged**
