### PR TITLE
Added 47 Degrees

### PR DESCRIPTION
**Pull request by raulraja**
https://47deg.github.io/

### CODE REVIEW

**Comment by staltz** [comment]
Hi @raulraja. Did you read the criteria?

**Comment by raulraja** [comment]
Hi @staltz.
I realized I have not included a link to a third party project, here is one http://ensime.org/
Also many of our employees spend paid in company time supporting projects such as https://github.com/typelevel/cats and others in the scala family beside those listed in the page which is the one hosted at 47 Degrees.

**Comment by staltz** [comment]
Can you get a statement from the company that this support is official? Part of the goal of this list is to get companies to publicly acknowledge their support for 3rd party open source. :)
A blog post or a company subpage is enough.

**Comment by raulraja** [comment]
Sure, here is one https://www.47deg.com/blog/ensime-sponsorship/

**Pull request merged**
