### PR TITLE
Added Activeloop (US) to the list

### PR DESCRIPTION
**Pull request by mikayelh**
added Activeloop and their project Hub - https://github.com/activeloopai/Hub

### CODE REVIEW

**Comment by staltz** [comment]
<h3>Criteria for inclusion</h3>
  <p>In order for an entry to be accepted into this list, the following criteria must be met</p>
  <ul>
    <li>Each entry is a COMPANY which systematically SUPPORTS some THIRD-PARTY OPEN SOURCE PROJECTS.</li>
    <li>Each entry should list the: (1) COMPANY name, (2) link(s) to blog post or page proving the support.</li>
  </ul>

**Comment by mikayelh** [comment]
Hi there,

Activeloop ([activeloop.ai](activeloop.ai)) is the company working on [Hub](https://github.com/activeloopai/Hub). The project is licensed under different name (Hub). A community member has recently written a blogpost confirming that on Towards Data Science [here](https://towardsdatascience.com/faster-machine-learning-using-hub-by-activeloop-4ffb3420c005). I just provided the homepage as the Docs for Hub are hosted there ([http://docs.activeloop.ai/](http://docs.activeloop.ai/)).

**Comment by staltz** [comment]
https://github.com/activeloopai/Hub does not have a copyright notice (who is the copyright holder?) and doesn't appropriately use the MPL license (it requires license headers on every source code file), so it's inconclusive whether Hub is authored by a third-party or first-party. Given it is hosted by the activeloop GitHub org, it is sensible to assume it's first-party.

**Comment by mikayelh** [comment]
@staltz , thank you so much for the feedback! We're just starting out, so it is all new for us - let me review and get back to you on this.

**Comment by mikayelh** [comment]
@staltz closing this for now! Thanks for your guidance.

**Pull request closed without merging**
